baseUrl: http://localhost
port: 3000
apollo:
  tracing: true
  debug: true
  playground: true
authentication:
  audience: https://xxx.com
  issuer: https://xxx.auth0.com/
  jwksUri: https://xxx.auth0.com/.well-known/jwks.json

